// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kluwybptynrikkmztofj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsdXd5YnB0eW5yaWtrbXp0b2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMTYzMjEsImV4cCI6MjA4NDc5MjMyMX0.smTKRKLgow2tAw9fpz8Co2u6kaLAmcsur9SxoT1QOc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});